name: .NET 6 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  SOLUTION_FOLDER: OnlineMarketplace.Products
  SOLUTION_FILE_PATH: OnlineMarketplace.Products.sln
  API_PROJECT_PATH: OnlineMarketplace.Products/OnlineMarketplace.Products.Api.csproj
  UNIT_TESTS_PROJECT_PATH: OnlineMarketplace.Products.Tests/OnlineMarketplace.Products.Tests.csproj
  INTEGRATION_TESTS_PROJECT_PATH: OnlineMarketplace.Products.IntegrationTests/OnlineMarketplace.Products.IntegrationTests.csproj

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      
      - name:  Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore ./$SOLUTION_FOLDER/$SOLUTION_FILE_PATH
      - name: Build
        run: dotnet build ./$SOLUTION_FOLDER/$API_PROJECT_PATH --no-restore
      - name: Test
        run: dotnet test ./$SOLUTION_FOLDER/$UNIT_TESTS_PROJECT_PATH --no-restore --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      - name: Integration tests
        run: dotnet test ./$SOLUTION_FOLDER/$INTEGRATION_TESTS_PROJECT_PATH --no-restore --verbosity normal
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '5 80'
        
      
